### ISSUE TITLE
load ubxlib library in esp idf

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#81] opened 2023-01-19 12:01 UTC
I can't get rid of the error message.
isp-idf v5.0

![image](https://user-images.githubusercontent.com/83282470/213437515-5abd5695-57f3-4881-85f9-66baa4935b56.png)

**Comment by alexmaron81** [comment] 2023-01-19 12:02
also for
![image](https://user-images.githubusercontent.com/83282470/213437919-05bea495-bea3-497d-82b9-b77b5ffc410e.png)

**Comment by RobMeades** [comment] 2023-01-19 12:49
Hi Alex: we test with ESP-IDF version 4, I didn't even know there was an ESP-IDF version 5.

**Comment by RobMeades** [comment] 2023-01-19 12:54
Seems that version 5 ESP-IDF has a few breaking changes.  My first guess would be that the above might be caused by this one:

https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/migration-guides/release-5.x/build-system.html#specify-component-requirements-explicitly

You could try adding `driver` to your list of required components.

**Comment by RobMeades** [comment] 2023-01-19 12:59
..and `esp_timer` as well.

**Comment by RobMeades** [comment] 2023-03-02 22:33
Closing this one: please re-open if necessary.

**Closed by RobMeades** 2023-03-02 22:33 UTC
