### ISSUE TITLE
SARA-R510S keeps CTS line sporadically high if DTR is used for power saving

### ISSUE THREAD

**Issue by eeFLis** [u-blox/ubxlib#192] opened 2024-02-01 10:07 UTC
Hi

maybe no ubxlib related problem, but perhaps you have already observed this behavior

If the DTR pin is used for power saving, the SARA R510 s module sporadically holds the CTS line high and no longer releases it.
the module is then no longer responsive.

we had the problem several times with the module firmware version 03.15, A00.01.
We hoped that this problem would be solved with the current module firmware version 03.30, A00.01, but the problem still occurs, even if it is much less frequent (after hours ).

Have you observed such behavior in your test environment?

**Comment by RobMeades** [comment] 2024-02-01 10:47
Hi @eeFLis: can't say this is something we've noticed, @philwareublox is going to check internally.

**Comment by RobMeades** [comment] 2024-02-01 11:03
@eeFLis: some questions.  You say that the module allows the `CTS` line to float high when `DTR` is used for power saving: is the module known to be otherwise functional when this problem has occurred, e.g. is `VINT` high, do you maybe get URC's turning up, that kind of thing?  Have you happened to be able to capture any HW traces (e.g. of the UART lines with a Saleae probe or similar) that show the relationship between the `DTR` line and `CTS` or other lines?

**Comment by eeFLis** [comment] 2024-02-01 11:29
Hi

I have attached the salea capture. However, this was already recorded some time ago with the module fw version 03.15, A00.01, but should show the problem
[SARA-R510S-01B-00 keep CTS high if DTR is used for power save.zip](https://github.com/u-blox/ubxlib/files/14124592/SARA-R510S-01B-00.keep.CTS.high.if.DTR.is.used.for.power.save.zip)

**Comment by eeFLis** [comment] 2024-02-01 12:27
Yes, we use the default value.
At the time of the salea capture, we certainly used a older version of the ubxlib.
If the default value for U_CELL_PWR_UART_POWER_SAVING_GSM_FRAMES was never adjusted in the ubxlib it was `AT+UPSV=1,1300`

Were you able to gather all the information from the salea capture or do you need additional information?

**Comment by RobMeades** [comment] 2024-02-01 12:44
I've been staring at it with the relevant expert internally.

If you look at the picture below, at the green marker is where the module emit a `+CSCON: 0`, so it is no longer RRC-connected and hence could go to sleep at any time (FYI, I'm told that when `DTR`-controlled sleep is in play the timeout in the `AT+UPSV=1,1300` doesn't apply, the module can go to sleep as soon as `DTR` permits it):

![image](https://github.com/u-blox/ubxlib/assets/6726745/dc8bde7a-af8d-48b5-beb0-9c49d32f52b3)

12 seconds later comes the problematic part, focusing on that:

![image](https://github.com/u-blox/ubxlib/assets/6726745/aef68cbf-68da-4014-96cb-6eb73d2053ca)

You can see, in the middle of the picture, that the module has allowed `CTS` to float high, without there being any `TXD` UART activity, which must be because the module has decided to go to 32 kHz sleep.  A short while later `CTS` goes low again, which is likely because some timed activity inside the module has caused it to wake up again, but only _briefly_.  `CTS` goes high again, and it is at about this time that the MCU pulls `DTR` low in order to send the next AT command.

Pure speculation, of course, but a guess would be that something to do with the fact that the module is autonomously coming out of 32 kHz sleep at the same moment as `DTR` goes high causes it to miss the `DTR` edge and remain in 32 kHz sleep.

Will continue to investigate...

**Comment by eeFLis** [comment] 2024-02-01 13:05
you mean  > at the same moment as `DTR `goes **low** right?
That would make sense

**Comment by RobMeades** [comment] 2024-02-01 13:29
Sorry, yes at the same moment as `DTR` goes low.

**Comment by RobMeades** [comment] 2024-02-01 13:31
Out of interest, are you able to read the state of the `CTS` pin from SW?  I had a feeling that STM32 wouldn't allow you to read the state of a pin that had been assigned to the UART?  Vaguely wondering if there might be a workaround of some form that you could do if you could read it.

**Comment by RobMeades** [comment] 2024-02-01 13:48
> Were you able to gather all the information from the Saleae capture or do you need additional information?

If you have additional Saleae captures of the problem then we could check if they look the same but no matter if you don't.

**Comment by eeFLis** [comment] 2024-02-01 14:38
Unfortunately I have no additional capture. 
I think the pin status can be read even if it is assigned to the UART.
Do you have an idea for a workaround if the pin could be read?  then I can test it shortly.

**Comment by RobMeades** [comment] 2024-02-01 15:47
One more question: do you know if the problem goes away if you set `UPSV=0`?  I mean I _assume_ it does, but I thought I'd ask.

**Comment by eeFLis** [comment] 2024-02-01 16:08
It already goes away when we set the `U_CFG_APP_PIN_CELL_DTR -1`.
However, this makes the application much less energy efficient.

**Comment by RobMeades** [comment] 2024-02-01 16:10
Thanks for confirming, understood, the aim is of course to retain the power-saving goodness, just wanted to be sure of the problem.

**Comment by RobMeades** [comment] 2024-02-01 22:52
Just for my information, if you set `U_CFG_APP_PIN_CELL_DTR -1`, so you aren't using the `DTR` pin to control UART power saving, you can still _have_ UART power saving of course, [provided](https://github.com/u-blox/ubxlib/blob/b849e705d69bc855d33b1e61f3b06cdbc5d14dbd/cell/api/u_cell_pwr.h#L476) you have implemented [uPortUartCtsSuspend()](https://github.com/u-blox/ubxlib/blob/b849e705d69bc855d33b1e61f3b06cdbc5d14dbd/port/api/u_port_uart.h#L421), which [should be there for STM32F4](https://github.com/u-blox/ubxlib/blob/b849e705d69bc855d33b1e61f3b06cdbc5d14dbd/port/platform/stm32cube/src/u_port_uart.c#L1646).  It may be _slightly_ more clumsy, since the `ubxlib` code will be waking the module up by prodding it with `AT` if the module has not been talked-to for more than 6 seconds, but it should still save pretty much the same amount of power.

Is this an approach you have tried?

**Comment by eeFLis** [comment] 2024-02-02 07:13
Yes we are using this approach.

That's what I tried to say with "we set `U_CFG_APP_PIN_CELL_DTR -1` instead of switching off power saving control completely with `UPSV=0`". Was not quite clear sorry.

The additional consumption is mainly noticeable after RRC connection ist released and the timer T3324 is running.
Any communication over UART during this time wakes up the module for 6 seconds, which is completely unnecessary.

I understand that the extra consumption doesn't look like much but if you're focusing on low power it's a crucial.
The low power features of the SARA R510s were one reason why we chose it.

**Comment by philwareublox** [comment] 2024-02-02 07:53
For my own clarity, are you saying without using the DTR line to drop the consumption of the UART you're then seeing the basic 6 second timeout for the UART. Whereas if you were able to use the DTR line successfully every time without this CTS issue, you can immediately control the UART on/off state as you want to.

**Comment by eeFLis** [comment] 2024-02-02 08:42
yes.

As an example:  during the active time (T3324) when data can still be received, the ubxlib is polling for new incomning data.
this means that the 6 second timeouts for the UART are never reached and the module do not entering power saving.

If the DTR line is used for power saving control the module can switch to power save mode immediately after the response.

**Comment by eeFLis** [comment] 2024-02-02 09:43
I think ubxlib already offers a solution for this. We use `uCellSockGetBytesPending()` to get the pending bytes reported by URC.
Only when some data has been received, we call `uSockRead()` or `uSockReceiveFrom()`

**Comment by eeFLis** [comment] 2024-02-02 09:46
However, this only solves the problem for the example I mentioned.
Any communication with the module during the active time (T3324) prevents the module from switching to power save mode for an unnecessarily long time.

**Comment by eeFLis** [comment] 2024-02-02 09:58
or do you see a problem with the use of `uCellSockGetBytesPending()` for the case described in the example?

**Comment by RobMeades** [comment] 2024-02-02 10:49
It should work, I guess the only problem might be if there is a lag between when the URC arrived to updated the number and when the application called `uCellSockGetBytesPending()`; that might cause the `uSockRead()` to fall into sleepy-time.  But even in the best case, where you read the data immediately, you will still get the 6 second lag.  And reducing the value of `U_CELL_PWR_UART_POWER_SAVING_GSM_FRAMES` will result in more laggy behaviour from the `ubxlib` APIs, since it will have to send an `AT` to wake the module up on more occasions.

We will continue thinking.

**Comment by eeFLis** [comment] 2024-02-02 10:59
In the meantime, are there any further findings as to where the error comes from when DTR is active?

**Comment by RobMeades** [comment] 2024-02-02 11:03
The expert internally is trying to reproduce the problem, just now looking to find the same FW version as you are using, to be quite sure about it.  It is a strange case: the `CTS` line was allowed to float high, indicating that the module has entered 32 kHz sleep, fully 3 milliseconds before the `DTR` line is asserted: that's quite a lot of time in module terms, hard to see what the relationship might be.

**Comment by RobMeades** [comment] 2024-02-02 15:43
FYI, the expert internally has your FW version now and is trying to script some form of sliding-delay-window of "AT/OK followed by a delay and then DTR raised" to see if he can make the problem occur; nothing from the few stabs he's had at this yet.

Wondering idly: I guess you have a callback hooked into [uCellNetSetBaseStationConnectionStatusCallback()](https://github.com/u-blox/ubxlib/blob/9ce2d92bb594f7d4010964a57ca2a28d9cf902f9/cell/api/u_cell_net.h#L704)?  I understand that the `+CSCON:x` URC, which that callback is triggered by, marks the start of T3324 - is there something (admittedly probably hacky and complicated) you could do with that and some "usually correct" guess at T3324 to hold off or bounce modem-access as appropriate?

**Comment by eeFLis** [comment] 2024-02-02 16:27
thanks for the update
yes we have a callback hooked into `uCellNetSetBaseStationConnectionStatusCallback()` which marks the start of T3324.
If I understand you correctly, you are thinking about a solution if the DTR problem cannot be solved and we have to fall back on the UART timeout right? That could be a possible option, but then we would still have the 6 second lag.

**Comment by RobMeades** [comment] 2024-02-02 18:56
> That could be a possible option, but then we would still have the 6 second lag.

True: if it is the case [as I think it is] that SARA-R5 cannot run the UART from a 32 kHz clock then every AT communication pulls the modem out of 32 kHz sleep and the only way to get back in is by letting `DTR` rise or by waiting for N (by default 6) seconds.

I was think that, if you could know that the module was not going to enter 32 kHz sleep _anyway_ (which might be when `CSCON: 1`) then, for those periods, you could just do anything on the AT interface, while for the times when the module _could_ enter 32 kHz sleep (which might be after `CSCON: 0`) you could, somehow, hold-off/batch-up/manage calls into `ubxlib` that might generate AT commands in order to maximize the power saved.

All a bit complex, and vague, I know.

**Comment by eeFLis** [comment] 2024-02-02 21:29
I have done a few more tests.
I think the first assumption that a `DTR `edge will be missed cannot be confirmed.
The module is no longer responsive in this state even after the `DTR `Line is pulled `high `and `low `again.
But I still have to verify it with a scope.

**Comment by RobMeades** [comment] 2024-02-02 21:50
Very interesting: would it be possible, once you get the module in this situation, to (a) measure VINT and maybe (b) [and I don't know how you'd do this] call [uPortUartCtsSuspend()](https://github.com/u-blox/ubxlib/blob/9ce2d92bb594f7d4010964a57ca2a28d9cf902f9/port/api/u_port_uart.h#L421), so that the UART will send anyway, and see if the module is responsive to `AT` commands at all (despite the state of CTS).

I'm not sure what kinds of module-based debug are available when the module is. apparently, in 32kHz sleep, but I'll ask.

I think that somehow putting a pattern to the conditions that cause the problem would be good - maybe attach something to measure power to see how sleepy it really is?

**Comment by RobMeades** [comment] 2024-02-06 13:52
The relevant expert internally has been trying quite hard but hasn't yet been able to reproduce a "module unresponsive" situation.  He's been focusing on the end of your Saleae trace, around here:

![image](https://github.com/u-blox/ubxlib/assets/6726745/445c9277-7dbc-43ef-9abf-4a0b6f3aa75a)

...where the DTR and CTS edges seem close:

![image](https://github.com/u-blox/ubxlib/assets/6726745/f81aea72-557b-4f32-8240-823164f3200f)

...and the kinds of thing he has been reproducing can be seen here in this [Otii power meter](https://www.qoitech.com/otii-arc-pro/) trace:

![image](https://github.com/u-blox/ubxlib/assets/6726745/60ec9fce-d7bc-40c1-98fd-424f59cf19b5)

..where it is looking pretty similar, but he has been unable to make the module unresponsive.

He suggests that, if it is possible, having some form of current-draw trace across the failure might tell him the state of the module at that time.

**Comment by eeFLis** [comment] 2024-02-06 17:17
It is not easy to reproduce the error as it sometimes only occurs after hours and seemingly random. 
I will attach the Otti and try to catch the error.

Come back when I have the requested data.

**Comment by eeFLis** [comment] 2024-02-06 19:44
Hi
Here are the recorded data. Module firmware 03.30, A00.01 was used for the recording.
[SARA-R510S-01B-01 keep CTS high if DTR is used for power save 06-02-2024.zip](https://github.com/u-blox/ubxlib/files/14185325/SARA-R510S-01B-01.keep.CTS.high.if.DTR.is.used.for.power.save.06-02-2024.zip)

Please note that the power profile includes the power consumption of all hardware components.

The recording shows the following sequence:

1. module is in PSM
2. wakes up and transmits some data through a UDP socket
3. return to PSM
4. wakes up and transmits some data through a UDP socket (**the error occurs here**)

**Comment by RobMeades** [comment] 2024-02-06 21:12
Oh, that's _excellent_, thanks very much for taking the time to do this, I will pass it on to the right person and get back to you.

**Comment by RobMeades** [comment] 2024-02-06 23:00
Browsing the Saleae log (I'll leave it up to the expert to view the OTII log as Windows Defender seems to have decided the OTII 3 application is a trojan on my laptop and keeps closing it), just to confirm the area of interest, it is here:

![image](https://github.com/u-blox/ubxlib/assets/6726745/e906f287-2e31-40dd-afa5-b6dbfacc8567)

...zooming in a bit:

![image](https://github.com/u-blox/ubxlib/assets/6726745/409b9764-6658-4415-9c6d-b8067a4be797)

...and zooming in again, the last thing that happens being an `AT+UCGED` query which seems to go fine, then:

![image](https://github.com/u-blox/ubxlib/assets/6726745/68c4323b-4172-422c-95df-6d65d3d7e49b)

...zooming in again, `DTR` is pulled low, which happens to be about 1 ms after `CTS` has gone high, and nothing happens, `CTS` remains high:

![image](https://github.com/u-blox/ubxlib/assets/6726745/75a3d7ba-5b14-4087-bd11-41fb987345d7)

...and stays there for 100 seconds, until you pull the plug.  During that time there are no URCs, VINT is high, but nothing at all of any use seems to be happening modem-wise.

Is that a correct interpretation?

**Comment by RobMeades** [comment] 2024-02-06 23:16
I've exported from the Salea log and attached here the AT exchange from the portion of interest, i.e. from coming out of PSM the second time.

[at.zip](https://github.com/u-blox/ubxlib/files/14187045/at.zip)

**Comment by eeFLis** [comment] 2024-02-07 07:55
I also noticed the absence of `+CSCON: 0`.
So I assume that the module is still connected. But the power profile says something else.

It looks like the module skips the active phase and starts immediately with T3324 without `+CSCON: 0`

![power profil](https://github.com/u-blox/ubxlib/assets/19823742/7064661a-a257-4753-b716-89addc5ac3bf)

**Comment by RobMeades** [comment] 2024-02-07 10:57
OK, our internal expert has been staring at the Saleae and Otii logs and is wondering if the issue is that, around the point of failure, `ubxlib` releases `DTR` (after the `AT+UCGED` query) and then the next `ubxlib` API call is made and so `ubxlib` pulls `DTR` low again, which in this case happens to be around 20 ms later; this time is relatively short.  Putting the HW into sleep and taking it out again apparently takes somewhere around 25ish ms so it _might_ be that short releases of `DTR` are the problem.

I will add code to `ubxlib` which remembers the time at which `DTR` was last released and, when a subsequent `ubxlib` API call is made, it will ensure that a minimum period [to be safe we will make that 50 ms] has passed before `DTR` is pulled low again and the `ubxlib` API call is executed.  If I push a preview branch of that code here, would you be able to try it?

**Comment by eeFLis** [comment] 2024-02-07 11:01
Yes for sure

**Comment by RobMeades** [comment] 2024-02-07 11:06
Actually, better than that, the code is already there (I'd obviously anticipated something of this nature and then forgotten): [U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS](https://github.com/u-blox/ubxlib/blob/ed16997a3cd576cae3371e69a545fdf411e29a4b/cell/src/u_cell_private.c#L71) is set to [U_AT_CLIENT_ACTIVITY_PIN_HYSTERESIS_INTERVAL_MS](https://github.com/u-blox/ubxlib/blob/ed16997a3cd576cae3371e69a545fdf411e29a4b/common/at_client/api/u_at_client.h#L423), which is 10 ms.

Could you try overriding `U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS` at build time to, say, 50 ms, see if that makes any difference?  Since the problem is statistical in nature I guess it might be difficult to be sure of course.

**Comment by eeFLis** [comment] 2024-02-07 11:13
I will do that. But even if the time is too short to wake up again, the module is in a state where consumption is much higher than it should be. 
![power profil DTR](https://github.com/u-blox/ubxlib/assets/19823742/901334f1-b5c6-4de1-8181-44826632d0a2)

**Comment by RobMeades** [comment] 2024-02-07 11:19
Yes: the thinking is that there is a bug somewhere in the module FW which means that, if `DTR` is raised and then lowered again too quickly, it goes off the rails, and in such a case it would never sleep.

Checking the code again, can I ask that, rather than defining `U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS` to be 50 ms, you define `U_AT_CLIENT_ACTIVITY_PIN_HYSTERESIS_INTERVAL_MS` to be 50 ms?  Reason is that, ultimately, it is the code within the AT client which controls the pin behaviour, rather than the code in the cellular area.

**Comment by RobMeades** [comment] 2024-02-07 11:26
Apologies for the confusion, please stick with setting `U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS` to be 50 ms, I should learn how to read my own code :-).

**Comment by eeFLis** [comment] 2024-02-07 12:26
Unfortunately, the error still occurs

Here is the recording
[capture U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS 50ms.zip](https://github.com/u-blox/ubxlib/files/14193763/capture.U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS.50ms.zip)

**Comment by eeFLis** [comment] 2024-02-07 12:31
This time the error occurs without the level of DTR altering. However, something seems to wake the module from sleep which causes the error.

![power profil CTS high](https://github.com/u-blox/ubxlib/assets/19823742/1dddfef9-9290-4567-8400-102ce6e082a3)

**Comment by RobMeades** [comment] 2024-02-07 12:33
Oh!  That is interesting: seems like an exceptionally short wake-up (low `CTS`) performed autonomously by the module.  I will alert our internal expert to the new information.

**Comment by RobMeades** [comment] 2024-02-07 12:41
Looking at the Saleae trace, the `DTR` toggles don't seem to have increased to 50 ms, still seem to around 50 ms, I wonder if there's something up with the hysteresis code?  Will check it...

![image](https://github.com/u-blox/ubxlib/assets/6726745/c5d956fc-dfee-4b84-96d1-dfab1b7e2fcd)

**Comment by eeFLis** [comment] 2024-02-07 13:05
should not have been set `U_CELL_PWR_UART_POWER_SAVING_DTR_HYSTERESIS_MS ` to 50ms instead of `U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS `?

**Comment by RobMeades** [comment] 2024-02-07 13:12
Gah, yes, you're right: there are two, one in the cellular code which is applied when things like CMUX need to disable `DTR`, and the other one in the AT Client for when _it_ is the one that has to toggle `DTR` (the usual case).  It is probably not a good idea that these are uncoordinated as well.

I will look at how to do this better but, as you say, set `U_CELL_PWR_UART_POWER_SAVING_DTR_HYSTERESIS_MS`, which is currently 20 ms, to be 50 ms for the purposes of this experiment.  My apologies.

**Comment by eeFLis** [comment] 2024-02-07 13:31
have checked it in the saleae trace should be ok now.

**Comment by eeFLis** [comment] 2024-02-07 13:34
The error has just occurred again. Do you need the trace?

**Comment by RobMeades** [comment] 2024-02-07 13:35
You're getting good at this :-|.  The trace might be useful, if possible.

**Comment by eeFLis** [comment] 2024-02-07 13:45
:-) Would be happier if the error disappeared.

Here the recording
[capture U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS 50ms -2.zip](https://github.com/u-blox/ubxlib/files/14194537/capture.U_CELL_PRIVATE_DTR_PIN_HYSTERESIS_INTERVAL_MS.50ms.-2.zip)

**Comment by eeFLis** [comment] 2024-02-14 09:11
Hi @RobMeades Is there any news on this topic?

**Comment by RobMeades** [comment] 2024-02-14 09:46
I was wondering that myself: apparently the internal expert was side-tracked onto something else, they will get back to it today.

**Comment by RobMeades** [comment] 2024-02-27 09:19
FYI, the internal expert is now back on this, investigating...

**Comment by eeFLis** [comment] 2024-02-27 12:02
Great, thanks for the information

**Comment by eeFLis** [comment] 2024-03-04 15:52
The good thing is that the cause of the problem could be identified.
Thank you for all the great support, if there is anything you want to test, please let me know.

**Comment by eeFLis** [comment] 2024-03-18 15:21
Hi @RobMeades Do you have any news from the HW expert on this?

**Comment by RobMeades** [comment] 2024-03-18 21:01
Sorry for the delay in this: I'm told the HW team are currently discussing it, will get back to you when they have something to say.

**Comment by eeFLis** [comment] 2024-06-18 05:54
Hi @RobMeades 
Do you know if there is the same restriction with the sara SARA-R52 series or could it be a solution to switch to this?

**Comment by RobMeades** [comment] 2024-06-18 07:09
Hi @eeFLis: that's an excellent question.  I've been prodding the HW people periodically and the last thing they said was that they would arrange a meeting with me to discuss the right way forward.  I've just asked them again and added this question to the agenda.

I can only apologize for the extreme delay here, will try to increase the pressure.

**Comment by eeFLis** [comment] 2024-06-18 07:36
Many thanks for your help.
We will produce another series of prototypes thats why I asked about the SARA-R52 series.

**Comment by RobMeades** [comment] 2024-06-20 14:55
Just had a call with one of the project managers on the HW side and some of the module SW team.  Not a huge update but guess is that SARA-R52 won't make a difference to the problem, since it appears to be on the baseband side and that is not changed in SARA-R52.

One thing that one of the SW guys has proposed is that maybe an external HW circuit could provide a fix: something which would gate DTR according to the state of CTS and delay the onwards transmission of DTR towards the module, a kind of HW workaround, hiding the problem from the module.  It would likely require something like this:

https://www.digikey.co.uk/en/products/detail/onsemi/MC74HC02ADR2G-Q/23329595

Of course, we have not actually tried this ourselves yet, just wondering if it is something that you could do within the constraints of your product or not?

**Comment by eeFLis** [comment] 2024-06-23 16:41
I don't understand how this should help, since the error occurs without the level of DTR altering.
[](https://github.com/u-blox/ubxlib/issues/192#issuecomment-1931950069)
Is clear what exactly is causing the problem?

**Comment by RobMeades** [comment] 2024-06-23 22:37
Hmmm, I had forgotten that case; the expert here made the problem state occur by toggling DTR constantly.  When he did this he found a window in which the module would fail to return from sleep (indicated by CTS staying high).  The implication of [your trace](https://github.com/u-blox/ubxlib/issues/192#issuecomment-1931950069) is that something about being in "sleep if DTR lets you" mode _can_ cause the problem, irrespective of the state of DTR, though I guess that would be more difficult to reproduce reliably.

I will add this specific data point to the internal ticket.

**Comment by RobMeades** [comment] 2024-07-09 14:20
[lack of an] update: another internal meeting, no significant progress to report I'm afraid, am persisting...

**Comment by RobMeades** [comment] 2024-07-17 10:07
@eeFLis: question - do you happen to recall if, when the problem occurs, the device ever spontaneously reboots (due to a watchdog timer going off) after a minute or not?

**Comment by eeFLis** [comment] 2024-07-17 10:52
I don't think I've ever seen a reboot but I can't say that for sure as I cropped all my recordings. The longest time recorded after the problem occurred was 20 seconds.

**Comment by philwareublox** [comment] 2024-08-08 11:13
Hi,
Sorry if I am missing something here which has already been discussed, but If you are using Flow control using the DTR line, why not use +UPSV=3 mode which uses the DTR line for power saving, instead of using +UPSV=1 mode which waits for the UART timeout? 
(We are still looking into this).
Phil.

**Comment by philwareublox** [comment] 2024-08-09 10:39
In our testing we are finding the watch dog resets the 'hung' module when in this state. The watch dog timer is about 45-60 seconds. Could you retest and wait for 90 seconds to see if the module automatically recovers?

**Comment by eeFLis** [comment] 2024-08-12 06:13
Hi @philwareublox 
I can do that but what is the intention?
To see if the module behaves the same in our tests or is it meant as a workaround?

**Comment by philwareublox** [comment] 2024-08-12 12:05
If you are happy with your resetting of the module within 20 seconds then this doesn't matter. 
We have tested this issue and found it does occur, but also recovers with a watch dog reboot after 60 seonds.

**Comment by eeFLis** [comment] 2024-08-12 12:57
Unfortunately, we can't use either option. Resetting the module or having the watchdog expire could cause issues in the upper layers of the communication protocol.

Could a firmware update for the module resolve this problem?

**Comment by philwareublox** [comment] 2024-08-14 10:00
Thanks for confirming. Yes it would be expensive and annoying to have to go through the communication yet-again because of a random reboot. 

We are still looking into this.

**Comment by philwareublox** [comment] 2024-08-14 18:26
Hi @eeFLis,

We have some low level improvements which show our reproduction of the issue is reduced, and continue to investigate. I will ask R&D if this is a state we could share an ENG version with you. 

Out-of-interest, can I ask what the application is? What is the protocol to send the data over the UBXLIB Socket API? 
Is there something you could implement that keeps track of the data already sent?

**Comment by eeFLis** [comment] 2024-08-19 07:05
Hi @philwareublox

I can provide details about our application, but it would need to be done through a private channel to comply with company policy.

We use LWM2M at the application layer, and I'm concerned that any workaround at this level would increase power consumption, which is the opposite of our goal for this Module feature.

**Comment by philwareublox** [comment] 2024-08-20 11:04
On the subject of the WatchDog, we can check what the reset/reboot reason was and then know if what you are seeing is the same thing we are seeing in R&D.
I have your email address from previous... I'll email.

**Comment by vaussard** [comment] 2024-08-20 11:45
Hi @RobMeades @philwareublox 

Sorry for jumping in, but I have the exact same issue as reported by @eeFLis with a SARA-R510 when using UPSV=3 and the DTR line. We are not using ubxlib, but we implemented the same workaround as U_CELL_PWR_UART_POWER_SAVING_DTR_HYSTERESIS_MS with some extra toggling of the DTR line when detecting that the modem is not waking up. This helps in some cases, but the modem still gets unresponsive a few times per day, which leads to annoying resets. We do not have such issues with the other u-blox modems or when disabling UPSV on the R5 (which is not a viable option for us).

If I understand correctly, you could have a FW update to mitigate that issue ? I would be more than happy to test on my side if this can help you. Do not hesitate to reach out to me if you need any information or more testing, since it is one of the biggest issue that we have with this modem.

**Comment by philwareublox** [comment] 2024-08-21 10:35
Hi,

If you have time, it is possible to get a crashdump from the module after the WatchDog resets the module. 
Using these commands: 

`at+uti="CUS:sdmosOnFatal=1,6,1,0,1,1,1"
at+uti="CUS:sdmosCrashDumpOnException=1,6,0,0,0,0,1,0,1"
at+uti="CUS:sdmosCrashDumpOnWatchdog=1,6,1,2,1,15,1,255,1"`

...you can enable the crashdump. This only needs to be sent once. 

Once set, and the module resets itself after 60-90 seconds when in this situation, the module will display a hex dump of the crash. We could use that then to confirm your issue is the same as what we can occasionally reproduce.

**Comment by vaussard** [comment] 2024-08-22 07:04
Thank you @philwareublox I will try to do that today, but this needs some adaptations in our firmware.
Is the hex dump sent before or after the greeting text ?

**Comment by vaussard** [comment] 2024-08-22 07:21
Trying these commands I get:
```
at+uti="CUS:sdmosOnFatal=1,6,1,0,1,1,1"
ERROR: UTI failure
OK
at+uti="CUS:sdmosCrashDumpOnException=1,6,0,0,0,0,1,0,1"
ERROR: UTI failure
OK
at+uti="CUS:sdmosCrashDumpOnWatchdog=1,6,1,2,1,15,1,255,1"
ERROR: UTI failure
OK

AT+UTI?
ERROR
AT+UTI=?
ERROR
```
The `UTI failure` does not sound good.

**Comment by philwareublox** [comment] 2024-08-22 09:43
Hi @vaussard  - sorry, it seems these commands are for development and not available/working for production devices.

**Comment by vaussard** [comment] 2024-08-26 07:49
I still gave it a try, but it has indeed no effect with my production modem. Even the watchdog does not seem to be enabled because there is no activity on the RX line after 5 minutes on "unresponsiveness".

Here is an example capture of this issue;

The last 2 commands before the modem becomes unresponsive. Even if DTR is toggled multiple times, the CTS line stays high forever:
![image](https://github.com/user-attachments/assets/6984bf79-696f-468e-9f62-6f50118ff71b)

Last command before becoming unresponsive:
![image](https://github.com/user-attachments/assets/a158e9a9-44ec-4036-b70f-b61b256f71df)

The last command was a AT+COPS? with a "OK" response, although we see the issue happening after pretty much any command:
![image](https://github.com/user-attachments/assets/b129fd5d-ce05-4e5c-a7cd-758195e63816)

@philwareublox what could we do to move forward with that issue ?

**Comment by vaussard** [comment] 2024-08-29 09:16
I updated to the latest released FW (SARA-R510S-01B-01 / 03.30) but it made no difference in the number of times per day that we have to reset the modem to keep it working.

This time it got stuck after `AT+UMETRIC?`:

![image](https://github.com/user-attachments/assets/13854696-580b-45e0-8871-31fafb602403)

![image](https://github.com/user-attachments/assets/5bd17c13-d01d-4a32-b9f2-411c06cc572e)

Unresponsive when toggling DTS:
![image](https://github.com/user-attachments/assets/34ac8bd2-e8f7-4e0e-89cf-d7b0b98cbc66)

I can easily test any new FW, once it is ready to be shared, on the prototype that I have on my desk.
Best regards

**Comment by philwareublox** [comment] 2024-09-02 09:54
Thanks for the update. We have a meeting tomorrow about this issue. 
It is very interesting there is no watchdog reset after 60-90 seconds though. Thanks for wait up to 5 mins to check this.

**Comment by eeFLis** [comment] 2024-09-05 07:28
Hi @philwareublox
Is there any update for us following the meeting?

**Comment by vaussard** [comment] 2024-09-12 08:27
Hello @philwareublox 

Thank you for your answer, even if it is not what I was hoping for. We will look into the -02B once it is available.

Regarding the existing -01B modules, do you know of any workaround?

We are currently using `UPSV=3`, but could mode 1 or 2 avoid or alleviate that issue ? This would need some significant changes in our code, so I prefer to make sure that it is not a dead-end before jumping into it.

**Comment by eeFLis** [comment] 2024-09-12 15:38
Hi @philwareublox

In this case, we will equip the upcoming prototypes with the SARA-R520 series, as it appears to be pin-compatible with the SARA-R510. Or is there anything specific we should take into account?

@RobMeades 
Is the SARA-R520 series fully supported by the ubxlib?

**Comment by RobMeades** [comment] 2024-09-12 15:40
> @RobMeades Is the SARA-R520 series fully supported by the `ubxlib`?

Yes, it is.

**Comment by eeFLis** [comment] 2024-09-20 12:19
Hi @RobMeades @philwareublox

I saw in the half-year results report that u-blox has stopped the development of their own cellular chips.
Does this mean the SARA-R52 will be the last series to feature this chipset?
What can we expect regarding long-term support?

**Comment by eeFLis** [comment] 2024-11-05 16:28
Hi @philwareublox

Any updates on this? 
We've received the new prototypes equipped with the SARA-R520-02B and are interested in testing a fix or prerelease if available?

**Closed** 2024-11-11 13:58 UTC
